### ISSUE TITLE
Something wrong with the speed test

### ISSUE THREAD

**Issue by dslisleedh** [NeonLeexiang/DLGSANet#10]
Hi, @NeonLeexiang,

First off, I'd like to thank you for your remarkable work. Your approach of using multi-head sliding windows as an alternative to shifted windows and sparse attention has truly been an inspiration.

However, I've noticed a potential oversight in the speed test.

In the speed test codes [[Link]](https://github.com/NeonLeexiang/DLGSANet/blob/21d5591184b722d0d13792630d8c48a4df939f1b/basicsr/archs/dlgsanet_arch.py#L961), it seems there are no codes that switch the model into test mode. This is vital, especially since your model leverages TLC which performs local ensembles of Restormer's attention results, incurring a significant number of loops and additional computational overhead.

I've benchmarked your model on my server (rtx3090) in both training and testing states. Here are the results:

Scale 4 / SwinIR vs DLGSANet / Train vs Test state:

**SwinIR (Train Mode):**
avg = 275.6369

**SwinIR (Test Mode):**
avg = 259.4968

**DLGSANet (Train Mode):**
avg = 186.1960

**DLGSANet (Test Mode):**
avg = 291.5465

The results in train mode show almost the same results in your paper. 
It might be beneficial to re-evaluate this.

Please let me know if there are any discrepancies or if further clarifications are needed.

Thank you for your time and dedication to this project.

**Comment by NeonLeexiang** [comment]
Hiii, 

We value your feedback. 

Since we implement TLC in our SparseGSA, the model runs at various speeds with and without TLC. 

While the model will have a faster inference time and similar performance in various benchmark datasets (Set5, Set14, B100), with a decrease in Urban100 and Manga109, without the use of the TLC. On the other side, The TLC enhances the performance in PSNR of some datasets while sacrificing the inference speed.

We will provide a thorough table of quantitative evaluations and the running time of our model with and without TLC in the supplementary. Additionally, we'll standardize our codes as soon as we can and deliver more thorough material (config file and pretrain models of lightweight models).
